---
version: "2.0"
services:
  service-1:
    image: fenildocker/llama3-70b
    expose:
      - port: 8501
        as: 8501
        to:
          - global: true
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units:
            - 5
        memory:
          size: 512Mi
        storage:
          - size: 16Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia: 
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 1000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
